services:
  data_collection:
    build: ./data_collection/.
    image: data_collection
    volumes:
      - ./storage:/usr/data
    env_file:
      - ./data_collection/.env
    container_name: data_collection
  feat_gen:
    build: ./feature_gen/.
    image: feat_gen
    volumes:
      - ./storage:/usr/data
    env_file:
      - ./feature_gen/.env
    container_name: feat_gen
    depends_on:
      data_collection:
        condition: service_completed_successfully
  train:
    build: ./training/.
    image: training
    volumes:
      - ./storage:/usr/data
    env_file:
      - ./training/.env
    container_name: train
    depends_on:
      feat_gen:
        condition: service_completed_successfully
