services:
  data_collection:
    build: ./data_collection/.
    image: data_collection
    volumes:
      - ./storage:/usr/data
    container_name: data_collection
  feat_gen:
    build: ./feature_gen/.
    image: feat_gen
    volumes:
      - ./storage:/usr/data
    container_name: feat_gen
    depends_on:
      data_collection:
        condition: service_completed_successfully
  train:
    build: ./training/.
    image: training
    volumes:
      - ./storage:/usr/data
    container_name: train
    depends_on:
      feat_gen:
        condition: service_completed_successfully
  inference:
    build: ./inference/.
    image: infer
    volumes:
      - ./storage:/usr/data
    container_name: infer
    depends_on:
      train:
        condition: service_completed_successfully
  flask_app:
    build: ./flask_app/.
    ports:
      - 5000:5000
    image: f_app
    volumes:
      - ./storage:/usr/data
    container_name: f_app
